import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({channel:'msedge',headless:true});
const errors=[];
try {
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  page.on('pageerror',e=>errors.push(e.message));
  const responsePromise=page.waitForResponse('**/api/funding');
  await page.goto('http://127.0.0.1:4180');
  const data=await (await responsePromise).json();
  await page.locator('.card').first().waitFor();
  const count=await page.locator('#rows tr[data-detail]').count();
  assert.ok(count>10);
  const original=await page.locator('.rate-cell:not(.missing-cell)').first().textContent();
  await page.getByRole('button',{name:'BPS',exact:true}).click();
  assert.notEqual(await page.locator('.rate-cell:not(.missing-cell)').first().textContent(),original);
  await page.getByRole('button',{name:'Year',exact:true}).click();
  assert.match(await page.locator('#basis').textContent(),/APR/);
  await page.getByRole('button',{name:'PERCENT',exact:true}).click();
  await page.getByRole('button',{name:'8H',exact:true}).click();
  await page.getByRole('searchbox').fill('BTC');
  assert.equal(await page.locator('#rows tr[data-detail="BTC"]').count(),1);
  await page.getByRole('button',{name:'BTC 즐겨찾기',exact:true}).click();
  await page.getByRole('searchbox').fill('');
  await page.locator('#favorites-only').check();
  assert.equal(await page.locator('#rows tr[data-detail]').count(),1);
  await page.reload();await page.locator('.card').first().waitFor();
  assert.equal(await page.getByRole('button',{name:'BTC 즐겨찾기',exact:true}).getAttribute('aria-pressed'),'true');
  await page.locator('#favorites-only').uncheck();
  await page.locator('[data-exchange="hyperliquid"]').click();
  await page.locator('[data-exchange="xyz"]').click();
  await page.locator('[data-exchange="variational"]').click();
  assert.equal(await page.locator('.card').count(),0);
  assert.equal(await page.locator('td[data-column="variational"]:visible').count(),0);
  await page.locator('[data-exchange="variational"]').click();
  await page.locator('.card').first().click();
  await page.locator('#detail[open]').waitFor();
  await page.locator('#chart-area').getByText(/수집|관측/).first().waitFor().catch(()=>{});
  const title=await page.locator('#detail-title').textContent();
  const symbol=title.split(' · ')[0];
  const row=data.rows.find(r=>r.symbol===symbol);
  await page.locator('#cost').fill('0');
  const gross=await page.locator('#calc-output strong').first().textContent();
  const expected=10000*Math.abs(row.nado.hourlyRate-row.variational.hourlyRate)*24;
  assert.ok(Math.abs(Number(gross.replace(/[^0-9.]/g,''))-expected)<.2);
  await page.locator('#cost').fill('10000');
  assert.match(await page.locator('#calc-output strong').last().textContent(),/−/);
  await page.locator('#notional').fill('');
  assert.equal(await page.locator('#calc-output strong').first().textContent(),'—');
  await page.getByRole('button',{name:'상세 닫기'}).click();
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();
  assert.match((await downloadPromise).suggestedFilename(),/\.csv$/);
  await page.locator('#guide-open').click();await page.locator('#guide[open]').waitFor();await page.getByRole('button',{name:'계산 기준 닫기'}).click();
  await mkdir('screenshots',{recursive:true});
  await page.screenshot({path:'screenshots/desktop.png',fullPage:false});
  await page.locator('#markets').scrollIntoViewIfNeeded();
  await page.screenshot({path:'screenshots/desktop-table.png'});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'screenshots/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.locator('.card').first().click();
  assert.equal(await page.evaluate(()=>document.querySelector('#detail').scrollWidth>document.querySelector('#detail').clientWidth),false);
  await page.screenshot({path:'screenshots/mobile-detail.png'});
  await page.getByRole('button',{name:'상세 닫기'}).click();
  await page.route('**/api/funding',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...data,sources:{...data.sources,nado:{...data.sources.nado,error:'HTTP 429'}},rows:data.rows.map(r=>({...r,comparable:false,spreadHourly:null,long:null,short:null,nado:r.nado?{...r.nado,stale:true}:undefined}))})}));
  await page.reload();await page.locator('#notice').waitFor();
  assert.equal(await page.locator('.card .position-path b').filter({hasText:'NADO'}).count(),0);
  await page.unroute('**/api/funding');
  await page.route('**/api/funding',route=>route.fulfill({status:502,body:'upstream unavailable'}));
  await page.reload();await page.locator('#notice').waitFor();assert.equal(await page.locator('.card').count(),0);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({browser:'Edge',commonMarkets:count,desktop:true,mobile:true,calculator:true,filters:true,csv:true,failureStates:true,errors},null,2));
} finally {await browser.close();}
